### PR TITLE
fix visual studio 2015 compile error

### PR DESCRIPTION
**Pull request by bugparty**

### CODE REVIEW

**Comment by gtorodelvalle** [comment]
Hi @TooTallNate , are you able to review and if appropriate merge this patch? :) Thanks!

**Comment by TooTallNate** [comment]
Let's give it a shot. I don't have a Windows machine readily set up at the moment, but let's see what Appveyor says about it.

**Comment by gtorodelvalle** [comment]
Hi @TooTallNate , I really appreciate it!!! :) I can confirm that it does work in Windows 10 Pro, version 1607, compilation number 14393.693 ;)

BTW, it would be great if you could generate a new release to avoid referencing the module as `"time": "git://github.com/TooTallNate/node-time.git#master"` in the `package.json` files :) Thanks once again!

**Comment by chabou** [comment]
I can confirm that it does work in Windows 8.1 too !

**Comment by TooTallNate** [comment]
v0.12.0 published to npm

**Pull request merged**
